baseurl      = "localhost"
title        = "Brian A. Heckman"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Subtitle for home
  homeSubtitle = "Welcome"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage"
  keywords = "homepage, blog"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"

[[params.social]]
    name = "email"
    url  = "Resume.pdf"

[[params.social]]
    name = "github"
    url  = "https://github.com/baheckman"

[[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/brian-heckman-20604182/"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Brian A. Heckman"
    subtitle = "Welcome"
    keywords = ""

    [languages.en.params.logo]
      logoText = "> $ cd /home/"
      logoHomeLink = "/"
      logoCursorColor = "#00758D"

  # And you can even create generic menu
  [[menu.main]]
    [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"
  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "projects/"